services:

  database:
    container_name: vet_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3307:3306'
    volumes:
      - ./.docker/database/config:/etc/mysql/conf.d
      - ./.docker/database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./.docker/database/mysql:/var/lib/mysql
    env_file:
      - ./.env
      - ./.env.local

  webserver:
    container_name: vet_nginx
    image: nginx:stable-alpine
    ports:
      - '8010:8010'
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    env_file:
      - ./.env
      - ./.env.local

  php:
    container_name: vet_php
    build:
      context: ./.docker/php
    volumes:
      - .:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - database
    env_file:
      - ./.env
      - ./.env.local

  mailer:
    container_name: vet_mailer
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'

